package:
    name: wera2netcdf
    version: "0.0.3"

source:
    fn: wera2netcdf-0.0.3.tar.gz
    url: https://pypi.python.org/packages/source/w/wera2netcdf/wera2netcdf-0.0.3.tar.gz
    md5: 1970a907d222905c262619d420cc4f8f

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pandas
        - netcdf4
        - pygc
        - pytz
        - python-dateutil

test:
  imports:
    - wera2netcdf
    - wera2netcdf.tests
  requires:
    - pytest

about:
  home: https://github.com/axiom-data-science/wera2netcdf
  license: MIT License
  summary: 'A utility to convert WERA total ASCII files into CF NetCDF files.'
