sudo: required
services: docker
branches:
  only:
    - test-install-extras

env:
  - DIMAGE=bekozi/ntest-ubuntu
  - DIMAGE=bekozi/nbuild-centos6

before_install:
  - docker run -id --name test-runner $DIMAGE bash

install:
  - docker exec test-runner bash -c "conda create -n test -c ioos ocgis nose esmpy"

script:
  - docker exec test-runner bash -c "source activate test && python -c \"from ocgis.test import run_simple; run_simple()\""
