package:
    name: metakernel
    version: "0.12.2"

source:
    fn: metakernel-0.12.2.tar.gz
    url: https://pypi.python.org/packages/source/m/metakernel/metakernel-0.12.2.tar.gz
    md5: 7ccd4cb4851c48dea35b95f600c8350d

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - ipython >=3.0
    run:
        - python
        - ipython >=3.0

test:
    imports:
        - metakernel
        - metakernel.magics
        - metakernel.magics.tests
        - metakernel.tests
        - metakernel.utils

about:
    home: https://github.com/Calysto/metakernel
    license: BSD License
    summary: 'Metakernel for Jupyter'
