package:
    name: simplejson
    version: "3.8.2"

source:
    fn: simplejson-3.8.2.tar.gz
    url: https://pypi.python.org/packages/source/s/simplejson/simplejson-3.8.2.tar.gz
    md5: 53b1371bbf883b129a12d594a97e9a18

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - simplejson
        - simplejson.tests
        - simplejson._speedups

about:
    home: http://github.com/simplejson/simplejson
    license: MIT License or Academic Free License (AFL)
    summary: 'Simple, fast, extensible JSON encoder/decoder for Python'

extra:
    recipe-maintainers:
        - ocefpaf
