package:
    name: oct2py
    version: "3.5.0"

source:
    fn: oct2py-3.5.0.tar.gz
    url: https://pypi.python.org/packages/source/o/oct2py/oct2py-3.5.0.tar.gz
    md5: 648ee3732b9784da778dfc400d91e0d3

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - ipython
        #- octave

#test:
    #imports:
        #- oct2py
        #- oct2py.ipython

about:
    home: http://github.com/blink1073/oct2py
    license: MIT License
    summary: 'Python to GNU Octave bridge --> run m-files from python'
