package:
    name: requests-toolbelt
    version: "0.5.1"

source:
    fn: requests-toolbelt-0.5.1.tar.gz
    url: https://pypi.python.org/packages/source/r/requests-toolbelt/requests-toolbelt-0.5.1.tar.gz
    md5: 580ab16edf9d1afad883623ba7873af9

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - requests >=2.0.1,<=3.0.0

test:
    imports:
        - requests_toolbelt
        - requests_toolbelt.adapters
        - requests_toolbelt.auth
        - requests_toolbelt.downloadutils
        - requests_toolbelt.multipart
        - requests_toolbelt.threaded
        - requests_toolbelt.utils

about:
    home: https://toolbelt.readthedocs.org
    license: Apache
    summary: 'A utility belt for advanced users of python-requests'
