package:
    name: pyhum
    version: "1.3.4"

source:
    fn: PyHum-1.3.4.tar.gz
    url: https://pypi.python.org/packages/source/P/PyHum/PyHum-1.3.4.tar.gz
    md5: 9836ac09b402a5181b53d3724d52da09

build:
    number: 0

requirements:
    build:
        - python >=2.7,<3
        - cython
        - numpy x.x
    run:
        - python
        - numpy x.x
        - scipy
        - pillow
        - matplotlib
        - scikit-learn
        - scikit-image
        - pyproj
        - joblib
        - simplekml
        - basemap
        - pyresample
        - dask

test:
    imports:
        - PyHum

about:
    home: https://github.com/dbuscombe-usgs/PyHum
    license: GNU Library or Lesser General Public License (LGPL)
    summary: 'Python/Cython scripts to read Humminbird DAT'
