package:
    name: compliance-checker
    version: "2.0.0"

source:
    fn: compliance-checker-2.0.0.tar.gz
    url: https://pypi.python.org/packages/source/c/compliance-checker/compliance-checker-2.0.0.tar.gz
    md5: 783cfa85acc6870dc3adf75b60418b72


build:
    number: 3
    entry_points:
        - compliance-checker = cchecker:main

requirements:
    build:
        - python >=2.7,<3
        - setuptools
    run:
        - python
        - owslib
        - wicken
        - lxml
        - cf_units
        - requests
        - python-dateutil
        - jinja2

test:
    imports:
        - compliance_checker
        - compliance_checker.cf
        - compliance_checker.tests
    commands:
        - compliance-checker --help

about:
    home: https://github.com/ioos/compliance-checker
    license:  Apache Software License
    summary: 'Checks Datasets and SOS endpoints for standards compliance'
