package:
    name: windspharm
    version: "1.3.2"

source:
    git_url: https://github.com/ajdawson/windspharm.git
    git_tag: v1.3.2

build:
    number: 0
    skip: True  # [win and py3k or win64]

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pyspharm

test:
    requires:
        - nose
    imports:
        - windspharm

about:
    home: http://ajdawson.github.io/windspharm/
    license: MIT
    summary: 'Python package for performing computations on global wind fields in spherical geometry.'
