package:
    name: regex
    version: "2016.01.10"

source:
    fn: regex-2016.01.10.tar.gz
    url: https://pypi.python.org/packages/source/r/regex/regex-2016.01.10.tar.gz
    md5: 17d03a6c7028b8f652915591bc5b5126

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - regex

about:
    home: https://code.google.com/p/mrab-regex-hg/
    license: Python Software Foundation License
    summary: 'Alternative regular expression module, to replace re.'
