package:
    name: petulant-bear
    version: "0.1.4"

source:
    git_url: https://github.com/ioos/petulant-bear.git
    git_tag: master

build:
    number: 0


requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - netcdf4
        - numpy
        - lxml

test:
    imports:
        - petulantbear

about:
    home: https://github.com/ioos/petulant-bear
    license:  GNU General Public License v3 (GPLv3)
    summary: 'Presents etree interface to netcdf4-python objects using NCML data model'
