package:
    name: xarray
    version: "0.7.0"

source:
    fn: xarray-0.7.0.tar.gz
    url: https://pypi.python.org/packages/source/x/xarray/xarray-0.7.0.tar.gz
    md5: 4b5767ca330de3c05237c721d4589d54

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pandas
        - netcdf4
        - scipy
        - bottleneck
        - dask >=0.6
        - h5netcdf
        - cyordereddict
        #- pynio

test:
    imports:
        - xarray
        - xarray.backends
        - xarray.core
        - xarray.test

about:
    home: https://github.com/pydata/xarray
    license: Apache Software License
    summary: 'N-D labeled arrays and datasets in Python'
