package:
    name: xarray
    version: "0.7.1"

source:
    fn: xarray-0.7.1.tar.gz
    url: https://pypi.python.org/packages/source/x/xarray/xarray-0.7.1.tar.gz
    md5: 22444bf16f9bd6d629385625df41e6b3

build:
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pandas
        - netcdf4
        - scipy
        - bottleneck
        - dask >=0.6
        - h5netcdf
        - cyordereddict
        - pynio  # [not py3k and not win]

test:
    imports:
        - xarray
        - xarray.backends
        - xarray.core
        - xarray.test

about:
    home: https://github.com/pydata/xarray
    license: Apache Software License
    summary: 'N-D labeled arrays and datasets in Python'

extra:
    recipe-maintainers:
        - ocefpaf
