package:
    name: pyscaffold
    version: "2.5.3"

source:
    fn: PyScaffold-2.5.3.tar.gz
    url: https://pypi.python.org/packages/source/P/PyScaffold/PyScaffold-2.5.3.tar.gz
    md5: 7c71ac59ff91fce924b162b778af8f41

build:
    number: 0
    skip: True  # [py35]
    preserve_egg_dir: True
    entry_points:
        - putup=pyscaffold.cli:run


requirements:
    build:
        - python
        - setuptools
        - setuptools_scm >=1.7
        - six
        - pbr >=1.6
    run:
        - python
        - six
        - pbr >=1.6

test:
    imports:
        - pyscaffold
        - pyscaffold.templates
    commands:
        - putup --help

about:
    home: http://pyscaffold.readthedocs.org/
    license: BSD License
    summary: 'Template tool for putting up the scaffold of a Python project'
