package:
    name: python-daemon
    version: "2.0.6"

source:
    fn: python-daemon-2.0.6.tar.gz
    url: https://pypi.python.org/packages/source/p/python-daemon/python-daemon-2.0.6.tar.gz
    md5: 049508c47c8fa054e91ec9a3c572f939

build:
    number: 0
    preserve_egg_dir: True
    skip: True  # [win]

requirements:
    build:
        - python
        - setuptools
        - docutils
    run:
        - python
        - docutils
        - lockfile >=0.10

test:
    imports:
        - daemon

about:
    home: https://alioth.debian.org/projects/python-daemon/
    license: Apache Software License
    summary: 'Library to implement a well-behaved Unix daemon process.'
