package:
    name: pycurrents
    version: "0.0.1.dev"

source:
    fn: tip.tar.gz
    url: http://currents.soest.hawaii.edu/hg/pycurrents/archive/tip.tar.gz

build:
    number: 0
    skip: True  # [win and py3k]

requirements:
    build:
        - python
        - numpy x.x
        - codas
        - mercurial  # [win]
        - mingwpy  # [win]
    run:
        - python
        - numpy x.x
        - codas
        - matplotlib
        - scipy
        - basemap
        - future

test:
    imports:
        - pycurrents

about:
    home: http://currents.soest.hawaii.edu/hg/pycurrents
    license: BSD
    summary: 'pycurrents'
