package:
    name: testfixtures
    version: "4.7.0"

source:
    fn: testfixtures-4.7.0.tar.gz
    url: https://pypi.python.org/packages/source/t/testfixtures/testfixtures-4.7.0.tar.gz
    md5: e892c81a6e223ff4a0cb301fe49b4ac0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - testfixtures

about:
    home: http://www.simplistix.co.uk/software/python/testfixtures
    license: MIT
    summary: 'A collection of helpers and mock objects for unit tests and doc tests.'
